In [1]:
import torch as t

## torch跟numpy的操作一模一樣

## 憶體狀態

In [2]:
t.Tensor(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
a=t.arange(0,6)
a

tensor([0, 1, 2, 3, 4, 5])

In [4]:
np_a=a.reshape(2,3)
Tensor_a=a.view(2,3)
print(np_a)
print(Tensor_a)
print(np_a.shape)
print(Tensor_a.shape)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([2, 3])
torch.Size([2, 3])


## unsqueeze(i)在第i維增加一個維度

In [5]:
Tensor_a_01=Tensor_a.unsqueeze(1)
Tensor_a_01.shape

torch.Size([2, 1, 3])

In [6]:
Tensor_a_10=Tensor_a.unsqueeze(0)
Tensor_a_10.shape

torch.Size([1, 2, 3])

In [7]:
Tensor_a.shape

torch.Size([2, 3])

In [8]:
a[1]=100
np_a

tensor([[  0, 100,   2],
        [  3,   4,   5]])

In [9]:
np_a.resize_(3,3)

tensor([[                0,               100,                 2],
        [                3,                 4,                 5],
        [29555336417116272, 29555366481887330, 31525390671741044]])

In [10]:
np_a_re1_3=np_a.resize_(1,3)

In [11]:
np_a_re1_3.resize_(3,3)

tensor([[                0,               100,                 2],
        [                3,                 4,                 5],
        [29555336417116272, 29555366481887330, 31525390671741044]])

In [12]:
a_12=t.arange(0,16)
a_12

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
a3_4=a_12.reshape(4,4)
a3_4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [14]:
a3_4[0]

tensor([0, 1, 2, 3])

In [15]:
a3_4[:,0]

tensor([ 0,  4,  8, 12])

In [16]:
a3_4[a3_4>3]

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
a3_4.long()#得到的是longtensor值

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [18]:
a3_4[t.LongTensor([0,3])]

tensor([[ 0,  1,  2,  3],
        [12, 13, 14, 15]])

## gather()選取對角線數字

In [19]:
a3_4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [20]:
a3_4_left_top=t.LongTensor([[0,1,2,3]])

In [21]:
a3_4.gather(0,a3_4_left_top)

tensor([[ 0,  5, 10, 15]])

In [22]:
a3_4.gather(0,a3_4_left_top).shape

torch.Size([1, 4])

In [23]:
a3_4.gather(0,a3_4_left_top).t()

tensor([[ 0],
        [ 5],
        [10],
        [15]])

## 右上到左下 t()為改變維度

In [24]:
a3_4_right_top=t.LongTensor([[3,2,1,0]]).t()

In [25]:
a3_4.gather(1,a3_4_right_top).t()

tensor([[ 3,  6,  9, 12]])

In [26]:
a3_4.gather(1,a3_4_right_top)

tensor([[ 3],
        [ 6],
        [ 9],
        [12]])

## 左下到右上

In [27]:
a3_4_right_top=t.LongTensor([[3,2,1,0]])

In [28]:
a3_4.gather(0,a3_4_right_top)

tensor([[12,  9,  6,  3]])

## 選取兩對角的元素

In [29]:
index=t.LongTensor([[0,1,2,3],[3,2,1,0]]).t()
a3_4.gather(1,index)

tensor([[ 0,  3],
        [ 5,  6],
        [10,  9],
        [15, 12]])

In [30]:
index=t.LongTensor([[0,1,2,3],[3,2,1,0]])
a3_4.gather(0,index)

tensor([[ 0,  5, 10, 15],
        [12,  9,  6,  3]])

## FloatTensor()裡面要list，可以做cos()三角函數等運算

In [31]:
list1=[]
for i in range(0,6):
    print(i)
    list1.append(i)

0
1
2
3
4
5


In [32]:
list1

[0, 1, 2, 3, 4, 5]

In [33]:
a2 = t.FloatTensor(list1).view(2,3) 

In [34]:
a2

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [35]:
b = t.cos(a2) 
print(b)

tensor([[ 1.0000,  0.5403, -0.4161],
        [-0.9900, -0.6536,  0.2837]])


In [36]:
a2%2

tensor([[0., 1., 0.],
        [1., 0., 1.]])

In [37]:
t.pow(a2,2) #等於a2**2 

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [38]:
t.clamp(a2,min=3) ##裡面的數值最小為3

tensor([[3., 3., 3.],
        [3., 4., 5.]])

## tensor float 轉 int，用long()

In [39]:
a2.type()

'torch.FloatTensor'

In [40]:
y=a2.long()
y

tensor([[0, 1, 2],
        [3, 4, 5]])

In [41]:
b=t.ones(2,3)
b.sum(dim=0)

tensor([2., 2., 2.])

In [42]:
b_T=b.sum(dim=0,keepdim=True)
b_T.shape

torch.Size([1, 3])

In [43]:
b_F=b.sum(dim=0,keepdim=False)
b_F.shape

torch.Size([3])

In [44]:
b.sum(dim=1)

tensor([3., 3.])

In [45]:
a=t.arange(0,6).view(2,3)

In [46]:
a.cumsum(dim=1)

tensor([[ 0,  1,  3],
        [ 3,  7, 12]])

## 廣播法則
### pytroch支援自動廣播，但是還是建議轉乘同維度，才不會出錯

In [47]:
a=t.ones(3,2)
b=t.ones(2,3,1)

In [48]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [49]:
a.reshape(2,3,1)

tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])

## expand不會占用額外空間，只會在需要的時候才擴充，可節省記憶體

In [50]:
b1=b.expand(2,3,2)

In [51]:
b1.shape

torch.Size([2, 3, 2])

## 轉道gpu上面運作.cuda()

In [52]:
if t.cuda.is_available():
    a=a.cuda()#使用gpu
    t.save(a,'a.pth')#將gpu的結果儲存到gpu中

In [53]:
a1=t.load('a.pth')
a1

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')

In [54]:
def for_loop_add(x,y):
    result=[]
    for i,j,in zip(x,y):
        result.append(i+j)
    return t.Tensor(result)
    

In [55]:
x=t.zeros(100)
y=t.ones(100)
%timeit -n 10 for_loop_add(x,y)


1.04 ms ± 457 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [56]:
%timeit -n 10x+y